[pytest]
markers = 
    smoke: Pruebas críticas de estabilidad inicial.
    regression: Suite completa de pruebas de regresión.
    integration: Pruebas de integración de componentes.
    api: Pruebas de validación de servicios de api.
    ui: Pruebas de validación de interfaz gráfica.